import React from 'react';
import { jsPDF } from 'jspdf';
import { SiteRequirements, ClimateData, ShelterParameters, SimulationResults, DesignRecommendation } from '../types';

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  site: SiteRequirements;
  climate: ClimateData;
  params: ShelterParameters;
  simulation: SimulationResults;
  recommendations: DesignRecommendation;
}

export const ReportModal: React.FC<ReportModalProps> = ({
  isOpen,
  onClose,
  site,
  climate,
  params,
  simulation,
  recommendations
}) => {
  if (!isOpen) return null;

  const handleDownloadPDF = () => {
    const doc = new jsPDF();

    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.setTextColor(2, 132, 199); // Sky blue
    doc.text("SHELTRON", 20, 22);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text("Smart Climate-Adaptive Shelter Design & Thermal Optimization Engine", 20, 28);
    doc.line(20, 32, 190, 32);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);
    doc.text("1. PROJECT & LOCATION SUMMARY", 20, 42);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Location: ${site.location_name} (${climate.climate_zone})`, 25, 50);
    doc.text(`Shelter Type: ${site.shelter_type} | Footprint: ${site.length_m}m x ${site.width_m}m (${site.length_m * site.width_m} m²)`, 25, 56);
    doc.text(`Occupants: ${site.occupants} | Target Budget: INR ${site.budget_inr.toLocaleString()}`, 25, 62);
    doc.text(`Peak Outdoor Summer Temp: ${climate.peak_summer_temp_c} °C | Wind: ${climate.wind_speed_ms} m/s ${climate.prevailing_wind_direction}`, 25, 68);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("2. SIMULATION & THERMAL PERFORMANCE", 20, 80);

    doc.setFont("helvetica", "normal");
    doc.text(`Equilibrium Indoor Temp: ${simulation.indoor_temp_c} °C (Reduction of ${simulation.temp_reduction_c} °C vs Peak)`, 25, 88);
    doc.text(`Thermal Comfort Index: ${simulation.thermal_comfort_score} / 100 (${simulation.thermal_comfort_status})`, 25, 94);
    doc.text(`Total Envelope Heat Gain: ${Math.round(simulation.heat_gain_w)} Watts`, 25, 100);
    doc.text(`Active Cooling Energy Requirement: ${simulation.cooling_energy_kwh_day} kWh / day`, 25, 106);
    doc.text(`Estimated Envelope Construction Cost: INR ${Math.round(simulation.estimated_cost_inr).toLocaleString()}`, 25, 112);
    doc.text(`Sustainability Score: ${simulation.sustainability_score} / 100 | Embodied Carbon: ${simulation.embodied_carbon_kg} kg CO2e`, 25, 118);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("3. CLIMATE-ADAPTIVE SPECIFICATIONS", 20, 130);

    doc.setFont("helvetica", "normal");
    const orientText = recommendations?.orientation_recommendation ? `${recommendations.orientation_recommendation.slice(0, 75)}...` : 'Optimized solar orientation';
    doc.text(`• Orientation: ${params.orientation_deg}° (${orientText})`, 25, 138);
    doc.text(`• Wall System: ${params.wall_material || 'Compressed Stabilized Earth Blocks'}`, 25, 144);
    doc.text(`• Roof Assembly: ${params.roof_material || 'Sloped Terracotta Ventilated Roof'}`, 25, 150);
    doc.text(`• Glazing & WWR: ${params.window_glazing || 'Double Glazed Low-E'} (${params.window_to_wall_ratio_pct}% WWR)`, 25, 156);
    doc.text(`• External Shading: ${params.shading_overhang_m}m depth overhang`, 25, 162);
    doc.text(`• Ventilation Strategy: ${params.cross_ventilation_strategy || 'Night Purge'}`, 25, 168);
    doc.text(`• Exterior Coating: ${params.paint_coating || 'High-Albedo Cool Paint'}`, 25, 174);

    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by SHELTRON Bioclimatic Engineering Platform - Smart India Hackathon Demo Edition", 20, 275);

    const safeLocation = (site?.location_name || "Shelter_Project").replace(/[^a-zA-Z0-9]/g, '_');
    doc.save(`SHELTRON_Shelter_Report_${safeLocation}.pdf`);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4">
      <div className="bg-white rounded-3xl max-w-2xl w-full p-6 shadow-2xl border border-slate-200 space-y-6 max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between pb-4 border-b border-slate-100">
          <div>
            <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2">
              <span>📄</span> SHELTRON Design & Performance Report
            </h2>
            <p className="text-xs text-slate-500">Comprehensive Engineering Dossier for {site.location_name}</p>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-full bg-slate-100 hover:bg-slate-200 text-slate-600 flex items-center justify-center text-sm font-bold transition-colors"
          >
            ✕
          </button>
        </div>

        {/* Executive summary table */}
        <div className="space-y-4 text-xs">
          <div className="bg-sky-50/70 p-4 rounded-2xl border border-sky-100 flex justify-between items-center">
            <div>
              <div className="text-[11px] font-semibold uppercase text-sky-700">Indoor Thermal Comfort</div>
              <div className="text-2xl font-bold text-slate-800">{simulation.indoor_temp_c}°C</div>
              <div className="text-slate-500">{simulation.temp_reduction_c}°C cooler than peak outdoor ambient</div>
            </div>
            <div className="text-right">
              <div className="text-[11px] font-semibold uppercase text-sky-700">Comfort Score</div>
              <div className="text-2xl font-bold text-emerald-600">{simulation.thermal_comfort_score} / 100</div>
              <div className="text-slate-500">{simulation.thermal_comfort_status}</div>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-slate-400 font-semibold block text-[10px] uppercase">Envelope Material Cost</span>
              <span className="text-base font-bold text-slate-800">₹{Math.round(simulation.estimated_cost_inr).toLocaleString()}</span>
              <span className="text-[10px] text-slate-500 block">Within target budget: {simulation.estimated_cost_inr <= site.budget_inr ? 'Yes ✓' : 'Exceeds target'}</span>
            </div>
            <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-slate-400 font-semibold block text-[10px] uppercase">Embodied Carbon</span>
              <span className="text-base font-bold text-slate-800">{simulation.embodied_carbon_kg} kg CO₂e</span>
              <span className="text-[10px] text-emerald-600 block">Eco-Score: {simulation.sustainability_score} / 100</span>
            </div>
          </div>

          <div className="p-4 rounded-xl border border-slate-200 space-y-2">
            <div className="font-bold text-slate-800">Key Architectural Recommendations:</div>
            <ul className="list-disc pl-5 space-y-1 text-slate-600">
              <li><b>Orientation:</b> {recommendations.orientation_recommendation}</li>
              <li><b>Walls:</b> {params.wall_material}</li>
              <li><b>Roof System:</b> {params.roof_material} with {params.roof_slope_deg}° slope</li>
              <li><b>Passive Shading:</b> {params.shading_overhang_m}m overhang with {params.window_to_wall_ratio_pct}% WWR</li>
              <li><b>Cooling:</b> {params.cross_ventilation_strategy}</li>
            </ul>
          </div>
        </div>

        <div className="flex justify-end gap-3 pt-3 border-t border-slate-100">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl text-xs font-semibold text-slate-600 hover:bg-slate-100 transition-colors"
          >
            Close
          </button>
          <button
            onClick={handleDownloadPDF}
            className="px-5 py-2.5 rounded-xl text-xs font-bold text-white bg-sky-600 hover:bg-sky-700 shadow-md shadow-sky-600/20 transition-all flex items-center gap-2"
          >
            <span>📥</span> Download Verified Engineering PDF
          </button>
        </div>
      </div>
    </div>
  );
};
